#!/usr/bin/env sh

BASEDIR=$(dirname "$0")

FILE=~/.local/share/TSMPModdedSeasonII/CONSOLELAUNCHER

if [ -f "$FILE" ]; then 
    open -a Terminal "$BASEDIR"/TSMPModdedSeasonII
else
    "$BASEDIR"/TSMPModdedSeasonII
fi
